# Generated by Django 4.2 on 2023-05-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
