# Generated by Django 4.2 on 2023-05-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0004_likequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
