# Generated by Django 4.2 on 2023-05-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0006_answer_rating_alter_profile_avatar_likeanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='posted_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
