# Generated by Django 4.2 on 2023-05-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0007_alter_question_posted_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
