# Generated by Django 4.2 on 2023-05-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0008_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('c', 'correct'), ('u', 'uncorrect')], default='u', max_length=1),
        ),
    ]
